sudo: required
services:
  - docker

before_install:
  - docker build -t osama210690/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true osama210690/docker-react npm run test -- --coverage
